-- AOM --

-- UPDATE PASSWORD
CREATE PROCEDURE UPDATE_PASSWORD
AS
UPDATE CUSTOMER
SET PASSWORD = ?
WHERE EMAIL = ? AND MSISDN = ? AND TC_NO = ?;

-- INSERT a new Customer
CREATE PROCEDURE INSERT_NEW_CUSTOMER
AS
INSERT INTO CUSTOMER ( CUST_ID, MSISDN, NAME, SURNAME, EMAIL, PASSWORD, SDATE, TC_NO ) 
VALUES ( ?, ?, ?, ?, ?, ?, ?, ? ); 

-- INSERT new Balance to a Customer
CREATE PROCEDURE INSERT_BALANCE_TO_CUSTOMER
AS
INSERT INTO BALANCE ( BALANCE_ID, PACKAGE_ID, CUST_ID, PARTITION_ID, BAL_LVL_MINUTES, BAL_LVL_SMS, BAL_LVL_DATA, SDATE, EDATE, PRICE, BAL_LVL_MONEY )
VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? );

-- INSERT_PACKAGE
CREATE PROCEDURE INSERT_PACKAGE
AS
INSERT INTO PACKAGE ( PACKAGE_ID, PACKAGE_NAME, PRICE, AMOUNT_MINUTES, AMOUNT_DATA, AMOUNT_SMS, PERIOD)
VALUES ( ?, ?, ?, ?, ?, ?, ? );

-- CHECK if customer exists or not
CREATE PROCEDURE CHECK_CUSTOMER_EXISTS_BY_EMAIL_AND_TCNO
AS
SELECT COUNT(*)
FROM CUSTOMER
WHERE EMAIL = ? AND TC_NO = ?;

-- GET Package Name by MSISDN
CREATE PROCEDURE GET_PACKAGE_NAME_BY_MSISDN
AS 
SELECT P.PACKAGE_NAME
FROM PACKAGE P 
WHERE P.PACKAGE_ID = 
	( SELECT B.PACKAGE_ID 
	  FROM BALANCE B
	  WHERE B.CUST_ID = 
		( SELECT C.CUST_ID
		  FROM CUSTOMER C
		  WHERE MSISDN =? 
		)
	);

-- GET Customer Password by MSISDN
CREATE PROCEDURE GET_CUSTOMER_PASSWORD_BY_MSISDN
AS
SELECT C.PASSWORD 
FROM CUSTOMER C
WHERE MSISDN = ?;

-- GET Customer ID by Email and TC no.
CREATE PROCEDURE GET_CUSTOMER_ID_BY_EMAIL_AND_TCNO
AS
SELECT CUST_ID
FROM CUSTOMER
WHERE EMAIL = ? AND TC_NO = ?;

-- GET MAX Customer ID 
CREATE PROCEDURE GET_MAX_CUSTOMER_ID
AS
SELECT MAX(CUST_ID)
FROM CUSTOMER;

-- GET MAX Balance ID
CREATE PROCEDURE GET_MAX_BALANCE_ID
AS
SELECT MAX(BALANCE_ID)
FROM BALANCE;

-- GET Customer Info by MSISDN
CREATE PROCEDURE GET_CUSTOMER_INFO_BY_MSISDN
AS 
SELECT CUST_ID, MSISDN, NAME, SURNAME, EMAIL, SDATE, TC_NO
FROM CUSTOMER
WHERE MSISDN = ?;

-- GET remaining Customer Balance by MSISDN
CREATE PROCEDURE GET_REMAINING_CUSTOMER_BALANCE_BY_MSISDN
AS 
SELECT
C.MSISDN,
B.BAL_LVL_DATA, 
B.BAL_LVL_SMS,
B.BAL_LVL_MINUTES,
B.SDATE,
B.EDATE
FROM CUSTOMER C 
JOIN BALANCE B ON C.CUST_ID = B.CUST_ID
WHERE C.MSISDN = ?;

-- GET Package info By Package ID
CREATE PROCEDURE GET_PACKAGE_INFO_BY_PACKAGE_ID
AS
SELECT 
PACKAGE_ID,
PACKAGE_NAME,
AMOUNT_MINUTES,
AMOUNT_SMS,
AMOUNT_DATA,
PERIOD
FROM PACKAGE
WHERE PACKAGE_ID = ?;


-- GET Package info by Msisdn
CREATE PROCEDURE GET_PACKAGE_INFO_BY_MSISDN
AS 
SELECT 
   P.PACKAGE_ID,
    P.PACKAGE_NAME,
    P.PRICE,
    P.AMOUNT_MINUTES,
    P.AMOUNT_DATA,
    P.AMOUNT_SMS,
    P.PERIOD
FROM
    PACKAGE P
JOIN
    BALANCE B
ON
    P.PACKAGE_ID = B.PACKAGE_ID
JOIN
    CUSTOMER C
ON
    B.CUST_ID = C.CUST_ID
WHERE
    C.MSISDN = ?;

-- CHF --

-- UPDATE SMS Balance by MSISDN
CREATE PROCEDURE UPDATE_CUSTOMER_SMS_BALANCE_BY_MSISDN
AS 
UPDATE BALANCE B
SET B.BAL_LVL_SMS = ?
WHERE B.CUST_ID =
	( SELECT C.CUST_ID 
	  FROM CUSTOMER C
	  WHERE C.MSISDN = ? );

-- UPDATE DATA Balance by MSISDN
CREATE PROCEDURE UPDATE_CUSTOMER_DATA_BALANCE_BY_MSISDN
AS 
UPDATE BALANCE B
SET B.BAL_LVL_DATA = ?
WHERE B.CUST_ID =
	( SELECT C.CUST_ID 
	  FROM CUSTOMER C
	  WHERE C.MSISDN = ? );
	
-- UPDATE MINUTES Balance by MSISDN
CREATE PROCEDURE UPDATE_CUSTOMER_MINUTES_BALANCE_BY_MSISDN
AS 
UPDATE BALANCE B
SET B.BAL_LVL_MINUTES = ?
WHERE B.CUST_ID =
	( SELECT C.CUST_ID 
	  FROM CUSTOMER C
	  WHERE C.MSISDN = ? );	

-- GET remaining SMS balance by MSISDN
CREATE PROCEDURE GET_CUSTOMER_REMAINING_SMS_BY_MSISDN
AS 
SELECT B.BAL_LVL_SMS
FROM BALANCE B
WHERE B.CUST_ID =
	( SELECT C.CUST_ID
	  FROM CUSTOMER C
	  WHERE C.MSISDN = ? );

-- GET remaining DATA balance by MSISDN  
CREATE PROCEDURE GET_CUSTOMER_REMAINING_DATA_BY_MSISDN
AS 
SELECT B.BAL_LVL_DATA
FROM BALANCE B
WHERE B.CUST_ID =
	( SELECT C.CUST_ID
	  FROM CUSTOMER C
	  WHERE C.MSISDN = ? );

-- GET remaining MINUTES/VOICE balance by MSISDN
CREATE PROCEDURE GET_CUSTOMER_REMAINING_MINUTES_BY_MSISDN
AS 
SELECT B.BAL_LVL_MINUTES
FROM BALANCE B
WHERE B.CUST_ID =
	( SELECT C.CUST_ID
	  FROM CUSTOMER C
	  WHERE C.MSISDN = ? );
	  
-- GET Package SMS Balance by MSISDN
CREATE PROCEDURE GET_PACKAGE_SMS_BALANCE_BY_MSISDN
AS
SELECT P.AMOUNT_SMS
FROM PACKAGE P
WHERE P.PACKAGE_ID = 
	( SELECT B.PACKAGE_ID
	  FROM BALANCE B
	  WHERE B.CUST_ID =
	  	  ( SELECT C.CUST_ID
	  	    FROM CUSTOMER C 
	  	    WHERE C.MSISDN =?
	  	    )
	);

-- GET Package DATA Balance by MSISDN
CREATE PROCEDURE GET_PACKAGE_DATA_BALANCE_BY_MSISDN
AS
SELECT P.AMOUNT_DATA
FROM PACKAGE P
WHERE P.PACKAGE_ID = 
	( SELECT B.PACKAGE_ID
	  FROM BALANCE B
	  WHERE B.CUST_ID =
	  	  ( SELECT C.CUST_ID
	  	    FROM CUSTOMER C 
	  	    WHERE C.MSISDN =?
	  	    )
	);

-- GET Package MINUTES/VOICE Balance by MSISDN
CREATE PROCEDURE GET_PACKAGE_MINUTES_BALANCE_BY_MSISDN
AS
SELECT P.AMOUNT_MINUTES
FROM PACKAGE P
WHERE P.PACKAGE_ID = 
	( SELECT B.PACKAGE_ID
	  FROM BALANCE B
	  WHERE B.CUST_ID =
	  	  ( SELECT C.CUST_ID
	  	    FROM CUSTOMER C 
	  	    WHERE C.MSISDN =?
	  	    )
	);
	  
-- GET User Email by MSISDN
CREATE PROCEDURE GET_USER_EMAIL_BY_MSISDN
AS
SELECT EMAIL
FROM CUSTOMER
WHERE MSISDN = ?;

-- GET Name by MSISDN
CREATE PROCEDURE GET_NAME_BY_MSISDN
AS
SELECT NAME
FROM CUSTOMER
WHERE MSISDN = ?;

-- GET Surname by MSISDN
CREATE PROCEDURE GET_SURNAME_BY_MSISDN
AS
SELECT SURNAME
FROM CUSTOMER
WHERE MSISDN = ?;

-- GET User Package ID by MSISDN
CREATE PROCEDURE GET_PACKAGE_ID_BY_MSISDN
AS
SELECT P.PACKAGE_ID
FROM PACKAGE P
JOIN BALANCE B ON B.PACKAGE_ID = P.PACKAGE_ID
JOIN CUSTOMER C ON C.CUST_ID = B.CUST_ID
WHERE C.MSISDN = ?;

	 
-- this procedure can cover the past 4 procedures together
-- you may remove it and write 4 methods instead of getUserDetails() and the UserDetails class also	 
-- GET CUSTOMER INFO & PACKAGE BY MSISDN
CREATE PROCEDURE GET_CUSTOMER_INFO_PACKAGE_BY_MSISDN 
AS
SELECT 
    C.NAME,
    C.SURNAME,
    C.EMAIL,
    P.PACKAGE_ID 
FROM 
    CUSTOMER C
JOIN 
    BALANCE B ON C.CUST_ID = B.CUST_ID
JOIN 
    PACKAGE P ON B.PACKAGE_ID = P.PACKAGE_ID
WHERE C.MSISDN = ?;
